# Generated by Django 4.2.2 on 2023-08-06 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='Cours_text',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='consulter',
            name='Raison_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='Date_actualisation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='Description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='Support',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='Titre_cours',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
