# Generated by Django 4.2.2 on 2023-08-06 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_remove_cours_cours_text_remove_cours_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='Auteur',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
