# Generated by Django 4.2.2 on 2023-09-09 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_alter_evenement_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='Niveau_concerné',
            field=models.CharField(choices=[('option1', 'Première année LPAS'), ('option2', 'Deuxième année LPAS'), ('option3', 'Troisième année LPAS')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
