# Generated by Django 4.2.2 on 2023-09-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='Support',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
