# Generated by Django 4.2.2 on 2023-09-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0012_alter_sujet_type_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Fond/')),
            ],
        ),
    ]
