# Generated by Django 4.2.2 on 2023-11-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0013_fond'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fond',
        ),
        migrations.AlterField(
            model_name='cours',
            name='Description',
            field=models.TextField(max_length=2000),
        ),
    ]
