# Generated by Django 4.2.2 on 2023-11-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0014_delete_fond_alter_cours_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='Niveau_concerné',
            field=models.CharField(choices=[('Première année LPAS', 'Première année LPAS'), ('Deuxième année LPAS', 'Deuxième année LPAS'), ('Troisième année LPAS', 'Troisième année LPAS')], max_length=100),
        ),
    ]
