# Generated by Django 4.2.2 on 2023-11-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0015_alter_cours_niveau_concerné'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='Support',
            field=models.FileField(upload_to='media/pdfs/'),
        ),
    ]
