# Generated by Django 4.2.2 on 2023-11-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0016_alter_cours_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='Support',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
