# Generated by Django 4.2.2 on 2023-11-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0017_alter_cours_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='Niveau_concerné',
            field=models.CharField(choices=[('option1', 'Première année LPAS'), ('option2', 'Deuxième année LPAS'), ('option3', 'Troisième année LPAS')], max_length=100),
        ),
    ]
