# Generated by Django 4.2.2 on 2023-11-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0018_alter_cours_niveau_concerné'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='Niveau_concerné',
            field=models.CharField(choices=[('option1', 'Licence 1'), ('option2', 'Licence 2'), ('option3', 'Licence 3'), ('option4', 'Master 1'), ('option5', 'Master 2'), ('option6', 'Master 3')], max_length=100),
        ),
    ]
