# Generated by Django 4.2.2 on 2023-11-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0019_alter_cours_niveau_concerné'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Support', models.FileField(upload_to='')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prénom', models.CharField(max_length=100)),
                ('Fonction', models.CharField(default=' ', max_length=100)),
                ('Mot', models.CharField(max_length=1000)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_fille', models.IntegerField()),
                ('Nombre_garçon', models.IntegerField()),
                ('Nombre_licence', models.IntegerField()),
                ('Nombre_master', models.IntegerField()),
                ('Nombre_professeur', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
