# Generated by Django 4.2.2 on 2023-11-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0020_fond_mot_statistique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mot',
            new_name='Mots',
        ),
    ]
