# Generated by Django 4.2.2 on 2023-11-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0021_rename_mot_mots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fond',
            name='Support',
            field=models.FileField(upload_to='static/Image/'),
        ),
    ]
