# Generated by Django 4.2.2 on 2023-11-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0022_alter_fond_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistique',
            name='Année_scolaire',
            field=models.CharField(default='', max_length=10),
        ),
    ]
