# Generated by Django 4.2.2 on 2023-12-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0023_statistique_année_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fond',
            name='Support',
            field=models.FileField(upload_to='media/'),
        ),
    ]
