# Generated by Django 4.2.2 on 2023-12-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0024_alter_fond_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePublicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('raison', models.TextField()),
                ('approuve', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
