# Generated by Django 4.2.2 on 2024-01-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0026_sujet_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='Niveau',
            field=models.CharField(choices=[('Bac', 'Bac'), ('Licence', 'Licence')], max_length=100),
        ),
    ]
