# Generated by Django 4.2.2 on 2024-01-06 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0027_alter_sujet_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='mots',
            name='Photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
