# Generated by Django 4.2.2 on 2024-02-26 01:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0033_membershiprequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembershipRequest',
            new_name='Membrepublicateur',
        ),
    ]
