# Generated by Django 4.2.2 on 2024-02-26 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0034_rename_membershiprequest_membrepublicateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrepublicateur',
            name='classe',
            field=models.CharField(choices=[('option1', 'Licence 1'), ('option2', 'Licence 2'), ('option3', 'Licence 3'), ('option4', 'Master 1'), ('option5', 'Master 2'), ('option6', 'Master 3')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membrepublicateur',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membrepublicateur',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membrepublicateur',
            name='numero',
            field=models.PositiveIntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membrepublicateur',
            name='raison',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membrepublicateur',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cours',
            name='Classe_auteur',
            field=models.CharField(choices=[('option1', 'Licence 1'), ('option2', 'Licence 2'), ('option3', 'Licence 3'), ('option4', 'Master 1'), ('option5', 'Master 2'), ('option6', 'Master 3')], max_length=100),
        ),
    ]
