# Generated by Django 4.2.2 on 2024-02-27 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0035_membrepublicateur_classe_membrepublicateur_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrepublicateur',
            name='prenom',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
