# Generated by Django 4.2.2 on 2024-02-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0036_membrepublicateur_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrepublicateur',
            name='classe',
            field=models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2'), ('Master 3', 'Master 3')], max_length=100),
        ),
    ]
