# Generated by Django 4.2.2 on 2024-07-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0038_adminrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='AdminRequest',
        ),
    ]
