# Generated by Django 4.2.2 on 2024-07-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0040_remove_cours_date_actualisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='Consultation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evenement',
            name='Date_actualisation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sujet',
            name='Consultation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sujet',
            name='Date_actualisation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='Auteur',
            field=models.CharField(max_length=100),
        ),
    ]
