# Generated by Django 4.2.2 on 2024-07-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0041_evenement_consultation_evenement_date_actualisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='Date_actualisation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='Classe_auteur',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='Auteur',
            field=models.CharField(max_length=100),
        ),
    ]
