# Generated by Django 4.2.2 on 2024-07-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0044_remove_cours_date_actualisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrepublicateur',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
