# Generated by Django 4.2.2 on 2024-07-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0047_alter_membrepublicateur_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='Classe_auteur',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='Classe_auteur',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='Classe_auteur',
        ),
    ]
