# Generated by Django 4.2.2 on 2023-08-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_cours_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='Consultation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
