# Generated by Django 4.2.2 on 2023-09-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_cours_niveau_concerné'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_test', models.CharField(choices=[('option1', 'Sélection'), ('option2', 'Présélection')], max_length=100)),
                ('Type_sujet', models.CharField(choices=[('option1', 'Epreuve'), ('option2', 'Corrigé')], max_length=100)),
                ('Année', models.PositiveIntegerField()),
                ('Support', models.FileField(upload_to='pdfs')),
                ('Auteur', models.CharField(max_length=100)),
                ('Classe_auteur', models.CharField(default=' ', max_length=100)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_actualisation', models.DateTimeField(auto_now=True)),
                ('Consultation', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
