# Generated by Django 4.2.2 on 2023-09-19 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0010_alter_sujet_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='Type_support',
            field=models.CharField(choices=[('option1', 'Photos'), ('option2', 'Vidéos')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
