# Generated by Django 4.2.2 on 2023-09-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0011_evenement_type_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='Type_test',
            field=models.CharField(choices=[('option1', 'Sélection'), ('option2', 'Présélection'), ('option3', 'Résultats')], max_length=100),
        ),
    ]
